using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
using System.Security.Claims;
using TTMS.Web.Data;
using TTMS.Web.Models.Entities;

namespace TTMS.Web.Middleware;

/// <summary>
/// Validates that the authenticated user still exists in the database on every request.
/// If the database was recreated (e.g., ttms.db deleted and regenerated by Migrate) while
/// the DataProtection keys persisted on disk, the auth cookie would still be valid but
/// reference a non-existent user. This causes SQLite "FOREIGN KEY constraint failed"
/// (Error 19) on any write operation because History.ChangedById, Project.CreatedById,
/// TaskItem.AssigneeId, TimeEntry.UserId, and Attachment.UploadedById all have FK
/// constraints to AspNetUsers.Id.
///
/// This middleware catches that scenario early and signs the user out, redirecting to
/// the login page with an explanatory message.
/// </summary>
public class ValidateUserMiddleware
{
    private readonly RequestDelegate _next;
    private readonly ILogger<ValidateUserMiddleware> _logger;

    public ValidateUserMiddleware(RequestDelegate next, ILogger<ValidateUserMiddleware> logger)
    {
        _next = next;
        _logger = logger;
    }

    public async Task InvokeAsync(
        HttpContext context,
        ApplicationDbContext db,
        SignInManager<ApplicationUser> signInManager)
    {
        // Only check authenticated users. Skip login/logout/register pages to avoid
        // redirect loops and allow the user to re-authenticate.
        var path = context.Request.Path.Value ?? string.Empty;
        var isAuthPage = path.StartsWith("/Identity/Account/Login", StringComparison.OrdinalIgnoreCase)
            || path.StartsWith("/Identity/Account/Logout", StringComparison.OrdinalIgnoreCase)
            || path.StartsWith("/Identity/Account/Register", StringComparison.OrdinalIgnoreCase)
            || path.StartsWith("/Identity/Account/AccessDenied", StringComparison.OrdinalIgnoreCase);

        if (context.User.Identity?.IsAuthenticated == true && !isAuthPage)
        {
            var userId = context.User.FindFirstValue(ClaimTypes.NameIdentifier);
            if (!string.IsNullOrEmpty(userId))
            {
                // Quick existence check — cheap query, no tracking.
                var exists = await db.Users.AsNoTracking().AnyAsync(u => u.Id == userId);
                if (!exists)
                {
                    _logger.LogWarning(
                        "User {UserId} has a valid auth cookie but does not exist in the database. " +
                        "Signing out and redirecting to login.", userId);

                    await signInManager.SignOutAsync();
                    context.Response.Redirect("/Identity/Account/Login?message=session_expired");
                    return;
                }
            }
        }

        await _next(context);
    }
}